name: Terraform Pipeline with Infracost Atlantis

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.5

      - name: Configure AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          echo "AWS credentials configured"

      - name: Install Infracost
        run: |
          curl -sL https://github.com/infracost/infracost/releases/latest/download/infracost-linux-amd64.tar.gz -o infracost-linux-amd64.tar.gz
          tar -xzf infracost-linux-amd64.tar.gz
          sudo mv infracost-linux-amd64 /usr/local/bin/infracost

      - name: Configure Infracost API key
        env:
          INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
        run: |
          echo "Infracost API key configured"

      - name: Terraform Init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform init

      - name: Terraform Validate
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform validate

      - name: Terraform Plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform plan -out=tfplan.binary

      - name: Convert Plan to JSON
        run: terraform show -json tfplan.binary > plan.json

      - name: Generate Cost Estimates
        env:
          INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
        run: infracost diff --path plan.json

      - name: Upload Cost Estimates (Optional)
        uses: actions/upload-artifact@v3
        with:
          name: cost-estimates
          path: infracost-results.json

  review:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - uses: actions/checkout@v3
      
      - name: Download Cost Estimates (Optional)
        uses: actions/download-artifact@v3
        with:
          name: cost-estimates

      - name: Review Cost Estimates
        run: |
          echo "Cost estimates are available for review."
